version: '3.8'

services:
  devops-exam:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: devops-exam-container
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    restart: unless-stopped
