apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exam-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-exam
  template:
    metadata:
      labels:
        app: devops-exam
    spec:
      containers:
      - name: devops-exam-container
        image: devops-exam:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: devops-exam-service
spec:
  type: NodePort
  selector:
    app: devops-exam
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005